import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";

import {
  captureRuleScreenshotCommand,
  captureRuleScreenshotInputSchema,
  declareComponentLiveHeroesCommand,
  declareComponentLiveHeroesInputSchema,
  requireActiveProjectCommand,
  scaffoldComponentHarnessCommand,
  scaffoldComponentHarnessInputSchema,
  verifyComponentLiveHeroesCommand,
  verifyComponentLiveHeroesInputSchema
} from "../runtime/commands";
import {
  failureResult,
  successResult,
  type RegisterIkranToolsDeps
} from "./shared";

export const DECLARE_COMPONENT_LIVE_HEROES_DESCRIPTION =
  "Compatibility-only legacy repair for pre-Preview-Registration harness records. Active components use record_artifact_written.componentPreview and Ikran's one shared adapter; do not author per-component harness routes for new work.";

export function registerRuleCaptureTools(
  mcp: McpServer,
  { ensureRuntime }: RegisterIkranToolsDeps
): void {
  mcp.registerTool(
    "capture_rule_screenshot",
    {
      description:
        "Capture a fresh screenshot of a prototype surface's CURRENT rendering for design-system rule provenance (layout / components.spec sourceCaptures). Runtime loads the surface's preview URL in headless Chromium, optionally crops to `crop`, and bakes each `annotations` rect into the PNG as a green highlight mark; crop and annotations are normalized floats in [0, 1] against the FULL page (x/y = top-left). Typical usage is two passes: capture plain, inspect the PNG, then capture again with crop + annotations. The PNG lands under design-system/captures/ and the returned artifactPath is what you declare in the rule's sourceCaptures — record_artifact_written rejects a declared capture file that does not exist. Never reuse another rule's existing capture file. During Initial Design System extraction, do not use this tool or Figma MCP to crop locators: Runtime derives those from Alignment node anchors and the seed screenshot. When no preview surface is ready and no Runtime evidence screenshot exists, capture via the host Figma MCP or omit sourceCaptures (honest unavailable only when there is no source node).",
      inputSchema: captureRuleScreenshotInputSchema
    },
    async (args) => {
      const rt = await ensureRuntime();
      const active = requireActiveProjectCommand();
      if (!active.ok) {
        return failureResult("capture_rule_screenshot", active.reason, rt);
      }
      const result = await captureRuleScreenshotCommand(active.project.path, args);
      return result.ok
        ? successResult(rt, result)
        : failureResult("capture_rule_screenshot", result.reason, rt);
    }
  );

  mcp.registerTool(
    "scaffold_component_harness",
    {
      description:
        "Compatibility-only legacy sizing-helper repair. Active components use the Runtime-owned shared Preview adapter generated by record_artifact_written.componentPreview; do not call this for new work.",
      inputSchema: scaffoldComponentHarnessInputSchema
    },
    async (args) => {
      const rt = await ensureRuntime();
      const active = requireActiveProjectCommand();
      if (!active.ok) {
        return failureResult("scaffold_component_harness", active.reason, rt);
      }
      const result = scaffoldComponentHarnessCommand(active.project.path, args);
      return result.ok
        ? successResult(rt, {
            ...result,
            next: "Legacy helper repaired. Active component work uses record_artifact_written.componentPreview."
          })
        : failureResult("scaffold_component_harness", result.reason, rt);
    }
  );

  mcp.registerTool(
    "declare_component_live_heroes",
    {
      description: DECLARE_COMPONENT_LIVE_HEROES_DESCRIPTION,
      inputSchema: declareComponentLiveHeroesInputSchema
    },
    async (args) => {
      const rt = await ensureRuntime();
      const active = requireActiveProjectCommand();
      if (!active.ok) {
        return failureResult("declare_component_live_heroes", active.reason, rt);
      }
      const result = declareComponentLiveHeroesCommand(
        active.project.path,
        args
      );
      return result.ok
        ? successResult(rt, {
            ...result,
            next: "Legacy declaration repaired. Active registrations verify automatically."
          })
        : failureResult("declare_component_live_heroes", result.reason, rt);
    }
  );

  mcp.registerTool(
    "verify_component_live_heroes",
    {
      description:
        "Compatibility-only legacy harness diagnostic. Active Preview Registrations verify default-first, cache, resume, and update eligibility automatically after record_artifact_written.componentPreview.",
      inputSchema: verifyComponentLiveHeroesInputSchema
    },
    async (args) => {
      const rt = await ensureRuntime();
      const active = requireActiveProjectCommand();
      if (!active.ok) {
        return failureResult("verify_component_live_heroes", active.reason, rt);
      }
      const result = await verifyComponentLiveHeroesCommand(
        active.project.path,
        args
      );
      if (!result.ok) {
        return failureResult("verify_component_live_heroes", result.reason, rt);
      }
      return successResult(rt, {
        ...result,
        ...(result.all_passed
          ? {
              next: "Legacy harness diagnostics passed. Active formalization eligibility remains Runtime-owned."
            }
          : {
              next: "Legacy harness diagnostics failed. Repair only the legacy record; new components use Preview Registration."
            })
      });
    }
  );
}
