// Component code-back is a live declaration, not a screenshot pipeline.
// The Agent writes standalone harness routes in the prototype app, declares
// those files, refreshes the Runtime-owned preview once, then atomically maps
// component entries to their live iframe routes here. No browser is launched
// and no PNG is generated by this command.

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import { closeProjectDb, openProjectDb, withProjectTransaction } from "./db";
import {
  buildLoggedEvent,
  insertEvent,
  logEventOnDb,
  logInvalidToolEvent
} from "./events";
import { emitRecordEvent } from "./record-bus";
import { locateEntryObject } from "./design-system-approval";
import { designSystemEntryContentDigest } from "./design-system-entry-provenance";
import {
  mergeEntrySourceCaptures,
  stripSourceCaptures
} from "./design-system-ingest";
import {
  isCaptureHarnessPath,
  validateDesignSystemJson,
  type DesignSystemFileKind
} from "./design-system-schema";
import { recordDesignSystemDigestIfConsistent } from "./design-system-sync";
import {
  stableJsonStringify,
  writeDesignSystemViewExport
} from "./design-system-view";
import {
  assertArtifactPathInProject,
  resolveProjectArtifactPath
} from "./evidence-package";
import {
  canonicalizeArtifactPath,
  SOURCE_ARTIFACT_TYPE_REGISTRY
} from "./source-artifact";

export interface ComponentLiveHeroMapping {
  entryId: string;
  surfaceId: string;
  harnessPath: string;
  harnessArtifactPath: string;
}

export type DeclareComponentLiveHeroesFailure = {
  ok: false;
  reason:
    | "empty_mappings"
    | "invalid_input"
    | "duplicate_entry"
    | "entry_not_found"
    | "entry_not_component_spec"
    | "no_code_links"
    | "code_file_missing"
    | "code_path_not_declared"
    | "code_path_not_code_artifact"
    | "harness_file_missing"
    | "harness_path_not_declared"
    | "harness_path_not_code_artifact"
    | "harness_surface_mismatch"
    | "surface_not_found"
    | "preview_unavailable"
    | "artifact_path_escape"
    | "artifact_file_missing"
    | "invalid_design_system_json"
    | "entry_not_in_source_file"
    | "write_failed"
    | "db_error";
  details?: unknown;
};

export type DeclareComponentLiveHeroesResult =
  | {
      ok: true;
      entries: Array<{
        entry_id: string;
        source_artifact_path: string;
        surface_id: string;
        harness_path: string;
        harness_artifact_path: string;
      }>;
      event_id: string;
    }
  | DeclareComponentLiveHeroesFailure;

type EntryRow = {
  id: string;
  entry_id: string;
  source_artifact_path: string;
  file_kind: string;
  status: string;
  value_json: string;
};

type NormalizedMapping = {
  entryId: string;
  surfaceId: string;
  harnessPath: string;
  harnessArtifactPath: string;
};

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

const CODE_ARTIFACT_TYPES: ReadonlySet<string> = new Set(
  Object.entries(SOURCE_ARTIFACT_TYPE_REGISTRY)
    .filter(([, spec]) => spec.validationClass === "code")
    .map(([type]) => type)
);

function sourceOnlyCaptures(
  entry: Record<string, unknown>,
  value: Record<string, unknown>
): unknown[] {
  return mergeEntrySourceCaptures(
    entry.sourceCaptures,
    value.sourceCaptures
  ).filter(
    (capture) => !(isPlainObject(capture) && capture.origin === "code")
  );
}

export function declareComponentLiveHeroes(
  projectPath: string,
  mappings: readonly ComponentLiveHeroMapping[]
): DeclareComponentLiveHeroesResult {
  if (mappings.length === 0) return { ok: false, reason: "empty_mappings" };
  const normalized: NormalizedMapping[] = mappings.map((mapping) => ({
    entryId: mapping.entryId.trim(),
    surfaceId: mapping.surfaceId.trim(),
    harnessPath: mapping.harnessPath.trim(),
    harnessArtifactPath: mapping.harnessArtifactPath.trim()
  }));
  if (
    normalized.some(
      (mapping) =>
        mapping.entryId.length === 0 ||
        mapping.surfaceId.length === 0 ||
        mapping.harnessArtifactPath.length === 0 ||
        !isCaptureHarnessPath(mapping.harnessPath)
    )
  ) {
    return { ok: false, reason: "invalid_input" };
  }
  const entryIds = normalized.map((mapping) => mapping.entryId);
  if (new Set(entryIds).size !== entryIds.length) {
    return { ok: false, reason: "duplicate_entry" };
  }

  const rows: EntryRow[] = [];
  const mappingByRow = new Map<string, NormalizedMapping>();
  {
    let db;
    try {
      db = openProjectDb(projectPath);
    } catch {
      return { ok: false, reason: "db_error" };
    }
    try {
      const exactEntryStmt = db.prepare(
        `SELECT id, entry_id, source_artifact_path, file_kind, status, value_json
         FROM design_system_entries WHERE id = ?`
      );
      const semanticEntryStmt = db.prepare(
        `SELECT id, entry_id, source_artifact_path, file_kind, status, value_json
         FROM design_system_entries
         WHERE entry_id = ? AND file_kind = 'component-spec'`
      );
      const declaredStmt = db.prepare(
        `SELECT artifact_type FROM source_artifacts WHERE path = ?`
      );
      const surfaceStmt = db.prepare(
        `SELECT s.readiness, s.stale, s.preview_url, r.prototype_root
         FROM prototype_surfaces s
         JOIN prototype_runs r ON r.id = s.prototype_run_id
         WHERE s.id = ?`
      );

      for (const mapping of normalized) {
        const exact = exactEntryStmt.get(mapping.entryId) as EntryRow | undefined;
        const row =
          exact ??
          (semanticEntryStmt.get(mapping.entryId) as EntryRow | undefined);
        if (!row) {
          return {
            ok: false,
            reason: "entry_not_found",
            details: { entryId: mapping.entryId }
          };
        }
        if (row.file_kind !== "component-spec") {
          return {
            ok: false,
            reason: "entry_not_component_spec",
            details: { entryId: row.entry_id, file_kind: row.file_kind }
          };
        }

        let value: unknown;
        try {
          value = JSON.parse(row.value_json) as unknown;
        } catch {
          return { ok: false, reason: "invalid_design_system_json" };
        }
        const rawLinks = isPlainObject(value) ? value.codeLinks : undefined;
        const codeLinks = Array.isArray(rawLinks)
          ? [...new Set(rawLinks.filter((link): link is string => typeof link === "string").map((link) => link.trim()).filter(Boolean))]
          : [];
        if (codeLinks.length === 0) {
          return {
            ok: false,
            reason: "no_code_links",
            details: { entryId: row.entry_id }
          };
        }
        for (const codeLink of codeLinks) {
          const canonical = canonicalizeArtifactPath(projectPath, codeLink);
          const absolute = resolveProjectArtifactPath(projectPath, codeLink);
          if (canonical === null || absolute === null) {
            return {
              ok: false,
              reason: "artifact_path_escape",
              details: { path: codeLink }
            };
          }
          if (!existsSync(absolute)) {
            return {
              ok: false,
              reason: "code_file_missing",
              details: { path: canonical }
            };
          }
          const declared = declaredStmt.get(canonical) as
            | { artifact_type: string }
            | undefined;
          if (!declared) {
            return {
              ok: false,
              reason: "code_path_not_declared",
              details: { path: canonical }
            };
          }
          if (!CODE_ARTIFACT_TYPES.has(declared.artifact_type)) {
            return {
              ok: false,
              reason: "code_path_not_code_artifact",
              details: { path: canonical, artifact_type: declared.artifact_type }
            };
          }
        }

        if (
          assertArtifactPathInProject(
            projectPath,
            mapping.harnessArtifactPath
          ) !== null
        ) {
          return {
            ok: false,
            reason: "artifact_path_escape",
            details: { path: mapping.harnessArtifactPath }
          };
        }
        const harnessCanonical = canonicalizeArtifactPath(
          projectPath,
          mapping.harnessArtifactPath
        );
        const harnessAbsolute = resolveProjectArtifactPath(
          projectPath,
          mapping.harnessArtifactPath
        );
        if (harnessCanonical === null || harnessAbsolute === null) {
          return { ok: false, reason: "artifact_path_escape" };
        }
        if (!existsSync(harnessAbsolute)) {
          return {
            ok: false,
            reason: "harness_file_missing",
            details: { path: harnessCanonical }
          };
        }
        const harnessDeclared = declaredStmt.get(harnessCanonical) as
          | { artifact_type: string }
          | undefined;
        if (!harnessDeclared) {
          return {
            ok: false,
            reason: "harness_path_not_declared",
            details: { path: harnessCanonical }
          };
        }
        if (!CODE_ARTIFACT_TYPES.has(harnessDeclared.artifact_type)) {
          return {
            ok: false,
            reason: "harness_path_not_code_artifact",
            details: {
              path: harnessCanonical,
              artifact_type: harnessDeclared.artifact_type
            }
          };
        }

        const surface = surfaceStmt.get(mapping.surfaceId) as
          | {
              readiness: string;
              stale: number;
              preview_url: string;
              prototype_root: string;
            }
          | undefined;
        if (!surface) {
          return {
            ok: false,
            reason: "surface_not_found",
            details: { surfaceId: mapping.surfaceId }
          };
        }
        const root = surface.prototype_root.trim();
        if (
          root.length > 0 &&
          harnessCanonical !== root &&
          !harnessCanonical.startsWith(`${root}/`)
        ) {
          return {
            ok: false,
            reason: "harness_surface_mismatch",
            details: {
              path: harnessCanonical,
              prototype_root: root,
              surfaceId: mapping.surfaceId
            }
          };
        }
        if (
          surface.readiness !== "ready" ||
          surface.stale !== 0 ||
          surface.preview_url.trim().length === 0
        ) {
          return {
            ok: false,
            reason: "preview_unavailable",
            details: {
              surfaceId: mapping.surfaceId,
              readiness: surface.readiness,
              stale: surface.stale !== 0,
              next: "Call record_preview once after all harness artifacts are declared."
            }
          };
        }

        rows.push(row);
        mappingByRow.set(row.id, {
          ...mapping,
          harnessArtifactPath: harnessCanonical
        });
      }
    } catch {
      return { ok: false, reason: "db_error" };
    } finally {
      closeProjectDb(db);
    }
  }

  const writtenFiles: Array<{
    absolutePath: string;
    relativePath: string;
    originalContent: string;
    newContent: string;
    parsed: Record<string, unknown>;
  }> = [];
  const dbValueByRow = new Map<string, string>();
  const dbCapturesByRow = new Map<string, string>();
  const approvedDigestByRow = new Map<string, string>();
  const restore = () => {
    for (const file of writtenFiles) {
      try {
        writeFileSync(file.absolutePath, file.originalContent, "utf8");
      } catch {
        // Best-effort restore; the original failure still stands.
      }
    }
  };

  for (const row of rows) {
    const absolutePath = resolveProjectArtifactPath(
      projectPath,
      row.source_artifact_path
    );
    if (absolutePath === null) {
      restore();
      return { ok: false, reason: "artifact_path_escape" };
    }
    let originalContent: string;
    try {
      originalContent = readFileSync(absolutePath, "utf8");
    } catch {
      restore();
      return { ok: false, reason: "artifact_file_missing" };
    }
    let parsed: unknown;
    try {
      parsed = JSON.parse(originalContent) as unknown;
    } catch {
      restore();
      return { ok: false, reason: "invalid_design_system_json" };
    }
    if (!isPlainObject(parsed)) {
      restore();
      return { ok: false, reason: "invalid_design_system_json" };
    }
    const entry = locateEntryObject(
      row.file_kind as DesignSystemFileKind,
      parsed,
      row.entry_id
    );
    if (!entry || !isPlainObject(entry.value)) {
      restore();
      return {
        ok: false,
        reason: entry ? "invalid_design_system_json" : "entry_not_in_source_file",
        details: { entryId: row.entry_id }
      };
    }
    const mapping = mappingByRow.get(row.id)!;
    const captures = sourceOnlyCaptures(entry, entry.value);
    const nextValue: Record<string, unknown> = {
      ...entry.value,
      liveHero: {
        surfaceId: mapping.surfaceId,
        harnessPath: mapping.harnessPath,
        harnessArtifactPath: mapping.harnessArtifactPath
      },
      sourceCaptures: captures
    };
    entry.value = nextValue;
    delete entry.sourceCaptures;
    const validation = validateDesignSystemJson("component-spec", parsed);
    if (!validation.ok) {
      restore();
      return {
        ok: false,
        reason: "invalid_design_system_json",
        details: { reason: validation.reason, details: validation.details }
      };
    }
    const newContent = `${stableJsonStringify(parsed)}\n`;
    try {
      writeFileSync(absolutePath, newContent, "utf8");
    } catch {
      restore();
      return { ok: false, reason: "write_failed" };
    }
    writtenFiles.push({
      absolutePath,
      relativePath: row.source_artifact_path,
      originalContent,
      newContent,
      parsed
    });
    dbValueByRow.set(row.id, JSON.stringify(stripSourceCaptures(nextValue)));
    dbCapturesByRow.set(row.id, JSON.stringify(captures));
    if (row.status === "formalized") {
      approvedDigestByRow.set(row.id, designSystemEntryContentDigest(entry));
    }
  }

  try {
    const transaction = withProjectTransaction(projectPath, (db) => {
      const now = new Date().toISOString();
      const entries = rows.map((row) => {
        const current = db
          .prepare(`SELECT 1 FROM design_system_entries WHERE id = ?`)
          .get(row.id);
        if (!current) throw new Error("entry_not_found");
        db.prepare(
          `UPDATE design_system_entries
           SET value_json = ?, source_captures_json = ?, updated_at = ?
           WHERE id = ?`
        ).run(
          dbValueByRow.get(row.id)!,
          dbCapturesByRow.get(row.id)!,
          now,
          row.id
        );
        const mapping = mappingByRow.get(row.id)!;
        const digest = approvedDigestByRow.get(row.id);
        if (digest) {
          logEventOnDb(db, "design_system_entry_approved", {
            source_artifact_path: row.source_artifact_path,
            entry_id: row.entry_id,
            content_digest: digest,
            from: "formalized",
            to: "formalized",
            via: "declare_component_live_heroes"
          });
        }
        return {
          entry_id: row.entry_id,
          source_artifact_path: row.source_artifact_path,
          surface_id: mapping.surfaceId,
          harness_path: mapping.harnessPath,
          harness_artifact_path: mapping.harnessArtifactPath
        };
      });
      const event = buildLoggedEvent("design_system_live_heroes_declared", {
        command: "declare_component_live_heroes",
        entries
      });
      insertEvent(db, event);
      return { entries, event };
    });

    for (const file of writtenFiles) {
      recordDesignSystemDigestIfConsistent(
        projectPath,
        "component-spec",
        file.parsed,
        file.relativePath,
        file.newContent
      );
      emitRecordEvent({
        kind: "design-system",
        action: "updated",
        id: file.relativePath,
        projectPath: path.resolve(projectPath)
      });
    }
    const exported = writeDesignSystemViewExport(projectPath);
    if (!exported.ok) {
      logInvalidToolEvent(
        projectPath,
        "invalid_output",
        "design_system_view_export",
        exported.reason
      );
    }
    return {
      ok: true,
      entries: transaction.entries,
      event_id: transaction.event.event_id
    };
  } catch {
    restore();
    return { ok: false, reason: "db_error" };
  }
}
